[env]
FONT_RASTERIZER_DEBUG = "true"
FONT_RASTERIZER_DEBUG_SHADER = "true"

[tasks.build-aatest]
description = "Run the aatest"
run = "cargo build --example aa_test"

[tasks.run-aatest]
description = "Run the aatest"
run = "./target/debug/examples/aa_test"
run_windows = ".\\target\\debug\\examples\\aa_test.exe"
depends = "build-aatest"

[tasks.build-aasvgtest]
description = "Run the aasvgtest"
run = "cargo build --example aa_svg_test"

[tasks.run-aasvgtest]
description = "Run the aasvgtest"
run = "./target/debug/examples/aa_svg_test"
run_windows = ".\\target\\debug\\examples\\aa_svg_test.exe"
depends = "build-aasvgtest"
