[package]
name = "rokid_3dof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
hidapi = "2.6.1"
bytemuck.workspace = true
cgmath.workspace = true
