[package]
name = "gui"
version = "0.1.0"
authors = ["mitoma <mutetheradio@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.105.0"
piston = "0.49.0"
text_buffer = { version = "0.1.0", path = "../text_buffer" }
serde = "1.0.101"
serde_derive = "1.0.101"