[package]
name = "win_hello"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.dependencies]
winit = { workspace = true }
windows-core = { workspace = true }
windows-future = { workspace = true }
windows-link = { workspace = true }
windows-time = { workspace = true }
pollster = { workspace = true }

[build-dependencies]
windows-bindgen = { workspace = true }
