name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:

  # check and build
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - target: x86_64-unknown-linux-gnu
            os: linux
            runs-on: ubuntu-20.04
          - target: x86_64-pc-windows-gnu
            os: windows
            runs-on: windows-latest
          - target: x86_64-apple-darwin
            os: macos
            runs-on: macos-latest

    runs-on: ${{ matrix.job.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - uses: mitoma/sver-actions/setup@v2
        with:
          os: ${{ matrix.job.os }}

      # os が linux の場合のみ libxcb関連のライブラリを apt でインストールする
      - name: install libxcb
        if: ${{ matrix.job.os == 'linux' }}
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev

      # ci phase
      - name: check all
        uses: mitoma/sver-actions/exec@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-${{ matrix.job.target }}
          command: |
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          cache_save_enable: true
          cache_key: ${{ matrix.job.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ matrix.job.target }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
